version: "3.8"

services:
  redis:
    image: "redis:6.0.9"
    container_name: redis_test
    ports:
        - "6379:6379"
    environment:
      - AbortOnConnectFail=false
      - AllowAdmin=true
      - ConnectRetry=2
      - ConnectTimeout=10000
      - Database=0
      - Ssl=false
      - password=*admin123*
  worker:
    build: .
    container_name: worker
    depends_on: 
      - redis
    environment:
      - Redis__Host=redis
      - Redis__Port=6379